### ISSUE TITLE
Gmail connection using fastapi-mail not working

### ISSUE THREAD

**Issue by rextech03** [sabuhish/fastapi-mail#103]
I have been struggling with send email using this module but even after enabling "LESS SECURE APP" on my gmail account I always get this error: fastapi_mail.errors.ConnectionErrors: Exception
raised Error connecting to smtp.gmail.com on port 587: [Errno 10061] Connect call failed ('74.125.140.109', 587), check your credentials or email service configuration.
I have checked my login detail but all to no avail

` message = MessageSchema(
subject="EasyShopas Account Verification Mail",
recipients=email, # List of recipients, as many as you can pass
body=template,
subtype="html"
)

fm = FastMail(conf)
await fm.send_message(message)

**Comment by sabuhish** [comment]
But this is not an issue of fastapi-mail, you should check your Gmail settings. you can use one-time app passwords for the app, or try to connect with TLS enabled. Again, not related to fastapi-mail actually.

**Comment by HemanthSai7** [comment]
How did you resolve this issue?? I;m facing the same issue.
