### ISSUE TITLE
validate_path issue for attachments

### ISSUE THREAD

**Issue by unidesigner** [sabuhish/fastapi-mail#108]
Hi there, thanks for the great library!
I was running into exceptions when I tried to attach files from an arbitary location in the filesystem.
Is there a reason why validate_path is implemented that way, or would you be willing to accept PRs to modify this behavior?
Thanks!

**Comment by Turall** [comment]
Hi @unidesigner , this is to prevent path traversal. Check this link for more information https://owasp.org/www-community/attacks/Path_Traversal

**Comment by sabuhish** [comment]
Hi, but this case applies only to the user that uses it as a developer, but if we remove that function, this will allow attackers to steal your other files that are stored in other directories. I don't think we would remove this function. It may seem just simple code for protection but does a lot of things if you see the whole picture of what can happen in the case of some serious projects that depend on this library. We should mind security. Thanks! 

For a simple solution for your case, I can tell you to fork the repo and remove this function and use it from your own GitHub repo.
