### ISSUE TITLE
Problem with httpx versions

### ISSUE THREAD

**Issue by Whatislove118** [sabuhish/fastapi-mail#109]
Hi, I have a problem with httpx version. 

`Because fastapi-mail (1.0.4) depends on httpx (>=0.19.0,<0.20.0)
   and no versions of fastapi-mail match >1.0.4,<2.0.0, fastapi-mail (>=1.0.4,<2.0.0) requires httpx (>=0.19.0,<0.20.0).
  So, because my-service depends on both fastapi-mail (^1.0.4) and httpx (^0.22.0), version solving failed.`

Is it really necessary to have this version of the library? The project is new, fresh, and there are the latest releases. Is this version chosen on purpose, or have you just not updated/tested with the latest version of httpx?
Thanks for attention.

**Comment by sabuhish** [comment]
Hi, version 1.0.6 has fixed this
