### ISSUE TITLE
Sending attachments from stream

### ISSUE THREAD

**Issue by VladislavPavlov2310** [sabuhish/fastapi-mail#114]
Hello, Is there any way to send attachments from stream and not file in path?
Maybe through UploadFile? Any ideas or examples?

**Comment by VladislavPavlov2310** [comment]
@sabuhish could you help with that or provide examples??

**Comment by sabuhish** [comment]
Hello, yes we have that option also. And we also provided examples of it. I guess you have not looked at the documentation, pls check the documentation, we have tried to put as much as the library provides.
https://sabuhish.github.io/fastapi-mail/example/#sending-files
