### ISSUE TITLE
multipart html and plain text emails

### ISSUE THREAD

**Issue by msb** [sabuhish/fastapi-mail#115]
Would it be possible to provide an example illustrating how to send an email with alternate plain text?.. as in
[the last example in these python email examples](https://docs.python.org/3/library/email.examples.html).

**Comment by sabuhish** [comment]
Hmm, I am pretty sure that we have provided enough examples for use cases.

https://sabuhish.github.io/fastapi-mail/example/
and if you want o plain text, you can specify it on `subtype`
https://github.com/sabuhish/fastapi-mail/blob/master/fastapi_mail/schemas.py#L41

**Comment by anpr** [comment]
But we'd like to send **both** the html attachment and the plaintext attachment. This is quite important as presumably many spam detectors don't like html-only emails.

**Comment by vatsal-fpl** [comment]
I am having an issue like when I try to create message Schema in different file attachment doesn't work, as it's provided in example. I am just passing the parameters shown in example.

**Comment by sabuhish** [comment]
We plan to update the documentation in the coming days and with this in mind, we will do minor refactorings and add a new feature. I will try to figure it out and let you know asap. Thanks for reporting.

**Comment by rememberlenny** [comment]
Any update?

**Comment by sabuhish** [comment]
This feature is now available in version 1.3.0, closing this issue.
