### ISSUE TITLE
Unable to Attach Custom SMTP Headers

### ISSUE THREAD

**Issue by SionAbes** [sabuhish/fastapi-mail#116]
## 👷 Problem
Unable to add custom SMTP headers to emails.

## 📄 Reason
To be able to attach [custom data to mailgun](https://documentation.mailgun.com/en/latest/user_manual.html#attaching-data-to-messages) using headers, which will allow us to track the status of emails (delivered, opened, rejected, etc..) with webhooks.

## 🔨 Solution
We use your library quite extensively at Tacto, and would like to open an PR to add this feature, but wanted to first discuss the options with you. As I see it, this would involve adding a new list of optional dicts to the [MessageSchema](https://github.com/sabuhish/fastapi-mail/blob/3a9090ad589ffcb08351e3cdef02db74d68d7d0e/fastapi_mail/schemas.py#L30) and then updating the `msg.py` to handle the adding of this. On a quick search, we saw you already use the `part.add_header()`. 

What do you think?

**Comment by sabuhish** [comment]
@SionAbes  please mind using 1.0.8, I had an issue with 1.0.7, I had to delete that release. Thanks again! Have a good evening! :)
