### ISSUE TITLE
Issue with Fastapi-mail using fakeredis internally

### ISSUE THREAD

**Issue by akshayjain847** [sabuhish/fastapi-mail#119]
since FastAPI-mail internally download fakeredis==1.7.* But even  latest fakeredis is not compatible with redis==4.2.* due to which I am unable to Use Redis==4.2.2 and FastAPI-mail. Can this be resolved somehow ?
<img width="1680" alt="Screenshot 2022-04-07 at 2 41 25 PM" src="https://user-images.githubusercontent.com/33511222/162164495-f0a99e29-d5ce-4281-bb4f-1600ff6948a1.png">

**Comment by sabuhish** [comment]
this issue most likely to be opened in fakeredis library not here since it is related to that.
