### ISSUE TITLE
Can't upgrade to FastaAPI 0.78.0 because "fastapi-mail 1.0.8 depends on FastaAPI 0.75.0

### ISSUE THREAD

**Issue by ramiswailem** [sabuhish/fastapi-mail#123]
How can I still use fastmail with FastaAPI 0.78.0?

**Comment by VolodymyrBor** [comment]
Have the same problem. I think it would be great to update the dependencies

**Comment by fullonic** [comment]
Same here. Have you seen any possible breaking changes if upgrading dependencies?

**Comment by so-rose** [comment]
Indeed, `fastapi-mail` 1.0.8 does not work with anything newer than `fastapi` 0.75.2 .

`fastapi` is pretty important security-wise to keep up to date. Any chance of updating the dependencies?

**Comment by sabuhish** [comment]
Hi, sorry for the late reply the issue should be resolved in the 1.0.9 version please install the latest version, closing the issue.
