### ISSUE TITLE
421 Service not available in local development.

### ISSUE THREAD

**Issue by philipokiokio** [sabuhish/fastapi-mail#127]
Hi, So I set up my applications mailer using the package. It worked seamlessly until recently. 9 out of 10 times throw this error. I have a production application where this code also lives and it works. 

`

Exception raised 421 Service not available, check your credentials or email service configuration.`

I used MailTrap, SendGrid and SendinBlue.

So I don't know what is wrong. Hence the issue.

**Comment by maestro-1** [comment]
Can you post your configurations and a sample of your code?

**Comment by philipokiokio** [comment]
Conguration.


```
load_dotenv()
config = ConnectionConfig(
    MAIL_USERNAME=os.getenv('MAIL_USERNAME'),
    MAIL_PASSWORD=os.getenv('MAIL_PASSWORD'),
    MAIL_FROM=os.getenv('MAIL_FROM'),
    MAIL_PORT=os.getenv('MAIL_PORT'),
    MAIL_SERVER=os.getenv('MAIL_SERVER'),
    MAIL_TLS=True,
    MAIL_SSL=False,
    TEMPLATE_FOLDER= Path(__file__).parent.parent/'templates/'
)

```



Where I am sending the mail with my router.
```

    mail_status = await mailer_utils.send_email_async(subject="Email Verification: Registration Confirmation",
    email_to=user_credentials.email, body=mail_body, template='email/email_verification.html')
```
