### ISSUE TITLE
Dependencies. Can it be cleaner?

### ISSUE THREAD

**Issue by maxzhenzhera** [sabuhish/fastapi-mail#130]
List of the current dependencies from **pyproject.toml**:
```
[tool.poetry.dependencies]
python = "^3.6.2"   
fastapi = "0.*" 
Jinja2 = "^3.0.1"
aiosmtplib = "^1.1.6"
pydantic = "^1.8.2"
email-validator = "^1.1.3"
aioredis = "^2.0.0"
httpx = "0.*"
blinker = "^1.4"
fakeredis = "^1.*"
python-multipart = "^0.0.5"
```
**aioredis** and **httpx** are used only in utils. I think it could be optional.
**fakeredis** is used only in tests. I think it could be in dev dependencies.
**fastapi** and **python-multipart** are not used directly at all.

### Please, explain to me, why we have so many required dependencies?

**Comment by sabuhish** [comment]
Hi @maxzhenzheram, 
you are right, I have thought about this also, during development we were using these libraries, and we moved to poetry on this PR #89 I realized these dependencies later. I will make another PR that moves these dependencies to the dev dependencies, thanks for pointing out this.

**Comment by sabuhish** [comment]
Done!
