### ISSUE TITLE
Typo in the FastApi-Mail Documentation

### ISSUE THREAD

**Issue by lucasbalieiro** [sabuhish/fastapi-mail#137]
Hi there, I'm glad to finally help with something.

https://sabuhish.github.io/fastapi-mail/#writing-unittests-using-fastapi-mail
![image](https://user-images.githubusercontent.com/37416577/181631147-268fdabb-918a-4853-898b-3b815fecf4a8.png)

If you look at the image above, there is a typo with a word that was meant to be: configuration.

I've tried to find the docs repo to send a PR, but I was not successful

**Comment by sabuhish** [comment]
Hi, thank you for finding this out! :)
