### ISSUE TITLE
No module named 'xxx' issue

### ISSUE THREAD

**Issue by schuberty** [sabuhish/fastapi-mail#142]
After I installed fastapi-mail 1.1.4 and set it up in my app, I started getting the following "no module found" messages when I import things related to the package, e.g.: 

```py
➜ pipenv run py
Loading .env environment variables...
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from fastapi_mail import ConnectionConfig
No module named 'aioredis'
No module named 'httpx'
```

I can delete my whole environment, reinstall it and it keeps coming back.

**Comment by zduvall** [comment]
I am getting this as well. It looks like it's coming from these two print statements in `fastapi_mail/email_utils/email_check.py`.

```py
try:
    import aioredis

    redis_lib = True
except ImportError as error:
    redis_lib = False
    print(error)

try:
    import httpx

    request_lib = True
except ImportError as error:
    request_lib = False
    print(error)
```
Can we remove the print statements?

**Comment by Feijo** [comment]
Any news about it?

**Comment by sabuhish** [comment]
Changes have already been merged and released, thanks for your help guys! I will close this issue now.
Please use version 1.1.5`. Thanks!
