### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by abushoeb** [sabuhish/fastapi-mail#145]
The module perfectly works on my local computer. However, the same application and credentials throw a 500 Internal Server Error on AWS. Here are the details error message:

```
{
  "status": false,
  "message": "Exception raised (535, 'Incorrect authentication data'), check your credentials or email service configuration"
} 
```

Did anyone else experience a similar problem?

**Comment by sabuhish** [comment]
Maybe the secrets you provide are hashed or something related to this, it should be a problem if you use the same authentication keys.
