### ISSUE TITLE
SSL/TLS and STARTTLS irritations

### ISSUE THREAD

**Issue by tammoippen** [sabuhish/fastapi-mail#146]
Hi there!

In find the documentation and usage for SSL/TLS and STARTTLS with this library irritating: in the documentation, you state

```
• MAIL_TLS : For TLS connection
• MAIL_SSL : For TLS connection
```

(see [here](https://github.com/sabuhish/fastapi-mail/blob/master/docs/getting-started.md?plain=1#L29-L30))

Then in the code, you use `MAIL_TLS` for STARTTLS and `MAIL_SSL` for SSL/TLS: [here](https://github.com/sabuhish/fastapi-mail/blob/master/fastapi_mail/connection.py#L49-L50)

From the aiosmtplib doc, `use_tls` is for TLS/SSL and it has an explicit `start_tls` flag: https://aiosmtplib.readthedocs.io/en/latest/client.html#connecting-over-tls-ssl (and the next section).

I would like to having the options renamed:

- `MAIL_TLS` ~> `MAIL_STARTTLS`
- `MAIL_SSL` ~> `MAIL_SSL_TLS`

But, i guess, that is a breaking change ... at least have the docs improved?

Thank you for the nice library!

**Comment by sabuhish** [comment]
Hi again, that is confising for sure. I will take into account your comments, and currently working on a PR.
I will just submit a PR soon, Let's have look at that there, agree?
