### ISSUE TITLE
Missing dependency on Starlette

### ISSUE THREAD

**Issue by synapticarbors** [sabuhish/fastapi-mail#149]
`fastapi-mail` has an [explicit dependency](https://github.com/sabuhish/fastapi-mail/blob/master/fastapi_mail/schemas.py#L7) on `starlette` that is missing in the `pyproject.toml`. It probably doesn't show up often because people are usually installing this package alongside `fastapi`, which pulls it in, but I noticed when I was packaging this package for conda-forge and building the package in isolation.

**Comment by sabuhish** [comment]
You are totally right, I have missed this. I was also using it without fastapi, I will take care of it today, thanks for pointing on it
