### ISSUE TITLE
Duplicated body content when opening emails sent via FastAPI-mail

### ISSUE THREAD

**Issue by DAguirreAg** [sabuhish/fastapi-mail#151]
After using one of the examples provided in the documentation (and modifying MAIL_USERNAME, MAIL_PASSWORD, MAIL_FROM and MAIL_SERVER accordingly to use gmail's smtp), I realized that the email's content I am receiving from FastAPI-main is duplicated. (First with the tags visible, and second with the tags being applied).

I directly copied the documentation's example and modified just the essentials so I am not sure if this is the expected behavior from FastAPI-mail.

![Screenshot from 2022-10-10 19-04-51](https://user-images.githubusercontent.com/50288378/194918947-a26f2eb9-c1fa-484a-8b84-b3718d9e3f46.png)

**Comment by sabuhish** [comment]
Hi @DAguirreAg  there is work going on it. #150 will have more changes to be committed soon. We will have newly updated README.md and docs. On the other hand, some functionality will be renewed. 

I suggest you read the discussion we had:
https://github.com/sabuhish/fastapi-mail/discussions/85

Thanks.
