### ISSUE TITLE
TypeError: duplicate base class TimeoutError

### ISSUE THREAD

**Issue by sheraff0** [sabuhish/fastapi-mail#155]
Upgrade to Python 3.11 breaks `fastapi-mail` dependency in my project.

The source is in `aioredis` package which is no longer maintained as a separate module and included into `redis-py`.

[Dependency](https://github.com/sabuhish/fastapi-mail/blob/2faf971af77f930430542a9f31bde67aa94de18b/fastapi_mail/email_utils/email_check.py#L9)

[Issue](https://github.com/aio-libs/aioredis-py/issues/1443)

Might be doing something wrong, but didn't find a better solution than this [quick fix](https://github.com/aio-libs/aioredis-py/issues/1443#issuecomment-1305089624).

**Comment by sabuhish** [comment]
hmm, that is interesting case, thanks for the opening the issue about it.
