### ISSUE TITLE
How to set a timeout for send_message ?

### ISSUE THREAD

**Issue by DaveMDS** [sabuhish/fastapi-mail#156]
Hi, 
is it possible to set a timeout for the FastMail.send_message function?
I didn't find nothing about timeout in the docs

Thanks in advance

**Comment by sabuhish** [comment]
Hi,
currently, this option is not supported. the default timeout is applied from the  `aiosmtplib` library

https://github.com/cole/aiosmtplib/blob/main/aiosmtplib/smtp.py#L46 

Thanks for mentioning this, we will work on it.

**Comment by sabuhish** [comment]
it is now avaliable on v1.2.2
