### ISSUE TITLE
Customize MIME "From" header

### ISSUE THREAD

**Issue by TheTimKiely** [sabuhish/fastapi-mail#16]
Hi,
Thanks for the great library.
I'm trying to customize how the sender appears in a email client.
I see that the spec supports adding a string before the sender's email address in the 'From' header.
It looks like this library maps the 'From' header directly to the sender's email address without the option to add a string.
In fastmail.py
    return await msg._message(self.config.MAIL_USERNAME)
In message.py
line 74
    async def _message(self,sender):
    self.message["From"] = sender
Do you have plans to add that to this library?
Thanks,
Tim

**Comment by sabuhish** [comment]
I am not totally sure if I understand, Could you please clarify a bit. Let me explain a bit for you,  MAIL_USERNAME is the username has been from config in order to be used as a sender. Password, ssl, tls option should be provided for this address. the sender cannot be changed through an option. Because config has been given regarding the email address other mail addresses cannot be used for the same config.

**Comment by TheTimKiely** [comment]
Hi,
The "FROM" header can have a name as well as the email address of the sender.  If there is a name, that is what will be shown in the mail client.
For example:
With this - self.message["From"] = 'name@email.com'
The email client will display 'name@email.com' as the sender.
But with this - self.message["From"] = 'My Name name@email.com'
The email client will display 'My Name' as the sender.

This would require another config field, something like SENDER_NAME.
And then when 
```python
async def _message(self,sender):
```
 is called, the two config fields could be contantenated.  Something like:
```python
    async def __preape_message(self, message):
        msg = MailMsg(**message.dict())
        if self.config.SENDER_NAME is not None:
            sender = f'{self.config.SENDER_NAME} {self.config.MAIL_USERNAME}'
        else:
            sender = self.config.MAIL_USERNAME
        return await msg._message(sender)
```

What do you think?

**Comment by sabuhish** [comment]
Yes, I tested it works like a charm! Can you make PR, thank you for diving in and offering a new feature. If you are going to make PR, I would ask you to check the latest version, there were minor changes.

**Comment by sabuhish** [comment]
Hey there, are you going to submit PR for this awesome feature?

**Comment by TheTimKiely** [comment]
Hi,
Sorry for the delay.
Yes, definitely will do.
I'll do it in the next day or two.
Thanks for following up,
Tim

**Comment by sabuhish** [comment]
it is fine, don't worry whenever you are ready you can submit. I just wanted to know if you still interested to submit.
