### ISSUE TITLE
Can't upgrade to fastapi==0.88.0 because "fastapi-mail 1.2.2 depends on starlette<0.22.0"

### ISSUE THREAD

**Issue by ilBEastli** [sabuhish/fastapi-mail#161]
The same problem as in previous issue https://github.com/sabuhish/fastapi-mail/issues/157 but for the next version of the library.
Do you consider to make less restrictive version dependency? 🙏🏻

**Comment by elpacificmb** [comment]
For your code to work, you need to force your requirements.txt to fastapi==0.86.0 and starlette==0.20.4, with that in place, you will have no issue for now.

**Comment by ilBEastli** [comment]
Yep but it keeps me and other users on old versions of libraries. That's pretty sad :(

**Comment by gbiz123** [comment]
I am having the same issue. For now I will just use smtplib to send my mail

**Comment by gbiz123** [comment]
It is I was able to resolve this with pip install fastapi=0.87.0 in a virtual environment

**Comment by ssproessig-thales** [comment]
maybe solved with #167

**Comment by sabuhish** [comment]
Hi there! could you guys please check version 1.2.4?

**Comment by rambo** [comment]
The caret version specifier is overly strict for 0.x versions, see https://github.com/python-gino/gino-starlette/pull/38 for details.

I also do not understand why python version is set to ^3.8.1 I could understand some much higher patch revision of 3.8 if it was *really* needed but .1 ?

**Comment by rememberlenny** [comment]
Can we go to 0.89.*?

**Comment by rambo** [comment]
@rememberlenny my PR hasvery loose starlette requirements (and there is no explicit requirement for fastapi version, the issues come from starlette version binds).

**Comment by sabuhish** [comment]
@rambo if your statements prove it I would be pleased about it, I thought I made it less restrictive on fastapi, but it seems like this issue arises again and again. Thanks for your work, will release a new version of the library.
