### ISSUE TITLE
Why is the validate_path necessary?

### ISSUE THREAD

**Issue by puehringer** [sabuhish/fastapi-mail#166]
First of all, thanks for the great library! 

In https://github.com/sabuhish/fastapi-mail/pull/17, the validate_path was introduced basically ensuring that the attachment is a child of the path in which python was executed. However, I don't see a good reason why that is important. 

Now imagine I start python in `/home/user`, but the attachment is placed in `/tmp/attachment.png`. This would now fail with: 
```
  File "/opt/venv/lib/python3.10/site-packages/fastapi_mail/schemas.py", line 67, in validate_file
    raise WrongFile('incorrect file path for attachment or not readable')
fastapi_mail.errors.WrongFile: incorrect file path for attachment or not readable
```

**Comment by sabuhish** [comment]
Hi @puehringer,
I agree with you, that changes blocks accessing files outside of the app. It is a restriction done by us. I am down to remove this check.

**Comment by sabuhish** [comment]
This feature was removed in `v1.2.3`, please use that version. Thanks for rising this issue
