### ISSUE TITLE
pip's dependency resolver does not currently take into account all the packages that are installed

### ISSUE THREAD

**Issue by nassimessaidi** [sabuhish/fastapi-mail#184]
When attempting to install the package, the following message appears:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastapi 0.70.0 requires starlette==0.16.0, but you have starlette 0.26.1 which is incompatible.
```

Even if the installation error occurs, attempting to run the application results in the following error:

```
AttributeError: 'FastAPI' object has no attribute 'debug'
```

This is the `requirements.txt` for the project:

```
...
fastapi==0.70.0
...
starlette==0.16.0
...
```

**Comment by Munalula-Sikazwe** [comment]
Are you running your project in a virtual environment ?   Ensure that the fastapi version your are running is the one found in your requirements.txt .  The most likely reason for your error is multiple installations  of fastapi  or multiple virtual environments.

**Comment by nassimessaidi** [comment]
Yes, I running the app in a virtual environment, I have only one virtual Env and one FastAPI installed which I listed in the requirements.txt above

**Comment by Munalula-Sikazwe** [comment]
If possible share a link to the github repo for the project So that I can have a further look.

**Comment by sabuhish** [comment]
Hi there, this is mostly related to using an old version of the library which is not compatible with other dependencies. Please make sure you upgrade the versions, this has nothing to do with fastapi-mail, therefore closing this issue.
