### ISSUE TITLE
Missing py.typed

### ISSUE THREAD

**Issue by Mark90** [sabuhish/fastapi-mail#187]
Hello,

I noticed that `py.typed` is missing in the repository, which means that type annotations in this project aren't fully utilized by mypy and editors. I didn't find an issue mentioning this before so perhaps it was just forgotten?

https://github.com/tiangolo/fastapi/commit/d675991a34098d3c367554ed5609ca34a1abbc3d
This commit on fastapi adds the same file and links to the relevant PEP about `py.typed`

Kind regards,
Mark

**Comment by sabuhish** [comment]
Hello,
You are right, it is missing `py.typed`,  will add it in the next MR. Thanks for finding out!

**Comment by sabuhish** [comment]
it is now available in the 1.2.8 version, thanks!
