### ISSUE TITLE
Dependency issues with Thirparty Authentication Library Supertokens

### ISSUE THREAD

**Issue by AmaruEscalante** [sabuhish/fastapi-mail#189]
Hi I'm trying to install this library alongside the `supertokens-python` library. This is the version of some packages I'm using:

[tool.poetry.dependencies]
python = "^3.10"
uvicorn = {extras = ["standard"], version = "^0.20.0"}
fastapi = "^0.95.0"
prisma = "^0.8.0"
supertokens-python = "^0.12.9"

`poetry add "fastapi-mail"       
Using version ^1.2.8 for fastapi-mail

Updating dependencies
Resolving dependencies... (0.0s)

  SolverProblemError

  Because no versions of fastapi-mail match >1.2.8,<2.0.0
   and fastapi-mail (1.2.8) depends on aiosmtplib (>=2.0,<3.0), fastapi-mail (>=1.2.8,<2.0.0) requires aiosmtplib (>=2.0,<3.0).
  And because supertokens-python (0.12.9) depends on aiosmtplib (1.1.6)
   and no versions of supertokens-python match >0.12.9,<0.13.0, fastapi-mail (>=1.2.8,<2.0.0) is incompatible with supertokens-python (>=0.12.9,<0.13.0).
  So, because fotosai-backend depends on both supertokens-python (^0.12.9) and fastapi-mail (^1.2.8), version solving failed.

  at ~/.poetry/lib/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes`

**Comment by AmaruEscalante** [comment]
I solved it by trying several releases of yours. Until I got one with no dependency issues. I got the following version working with each other

fastapi-mail = "1.1.1"

**Comment by sabuhish** [comment]
closing this issue, it is supertokens-python lib issue, not fastapi-mail, they should be updating dependencies.
