### ISSUE TITLE
Which version of fastapi-mail I can use with fastapi 0.99.1 and pydantic 1.10.10?

### ISSUE THREAD

**Issue by jabajke** [sabuhish/fastapi-mail#199]
I use fastapi version 0.99.1 and pydantic 1.10.10, so when I try
`poetry add fastapi-mail`
then I get
```
  SolverProblemError

  Because no versions of fastapi-mail match >1.4.1,<2.0.0
   and fastapi-mail (1.4.1) depends on pydantic (>=2.0,<3.0), fastapi-mail (>=1.4.1,<2.0.0) requires pydantic (>=2.0,<3.0).
  And because fastapi (0.99.1) depends on pydantic (>=1.7.4,<1.8 || >1.8,<1.8.1 || >1.8.1,<2.0.0)
   and no versions of fastapi match >0.99.1,<0.100.0, fastapi-mail (>=1.4.1,<2.0.0) is incompatible with fastapi (>=0.99.1,<0.100.0).
  So, because bbm-backend depends on both fastapi (^0.99.1) and fastapi-mail (^1.4.1), version solving failed.
  ```
there is list of my dependencies
fastapi==0.99.1
SQLAlchemy==2.0.17
alembic==1.11.1
psycopg2-binary==2.9.6
asyncpg==0.27.0
passlib==1.7.4
uvicorn==0.22.0
pytz==2023.3
python-multipart==0.0.6
PyJWT==2.7.0
python-dotenv==1.0.0
pandas==2.0.3
openpyxl==3.1.2
numpy==1.25.2
boto3==1.28.17
celery[redis]==5.3.1

**Comment by fchancel** [comment]
You can try with v1.3.1

**Comment by Grenate22** [comment]
How do you solve it ?

**Comment by sabuhish** [comment]
Fastapi-mail depends on pydantic ^2.0 and fastapi ^0.100. Please update your libraries
