### ISSUE TITLE
email-validator lib conflict

### ISSUE THREAD

**Issue by PaoFrito** [sabuhish/fastapi-mail#207]
I saw that this lib uses email-validator lib. I find it while I was working on one of my projects that is using email-validator lib (on the latest version), and after downloading the fastapi-mail lib, dependency conflicts starts to occur. I realy like this lib, it's simple and easy, witch makes the development of email features really fast. Anyone knows how to fix this dependency problem?

**Comment by sabuhish** [comment]
#218 will update.
