### ISSUE TITLE
Sending Emails As Html

### ISSUE THREAD

**Issue by maestro-1** [sabuhish/fastapi-mail#21]
Fastapi mail does not support sending mail by default. In fact, it seems to only support simple string emails. It is a great library but it can be more feature rich if it supported html emails. In one of my more recent fastapi projects, I worked with html emails. I liked this library so much for how minimalistic it is and how it can take off some extra pieces of code from my projects, but seeing that so far this feature has been integral to all my more recent projects and isn't present here and I thought it only right to make the push.

My Proposition:
###  Using Jinja2 HTML Templates

The email folder must be present within your application working directory.

In sending HTML emails, the CSS expected by mail servers -outlook, google, etc- must be inline CSS. Fastapi mail passes _"body"_ to the rendered template. In creating the template for emails the dynamic objects should be used with the assumption that the variable is named "_body_" and that it is a python dict.

check out jinja2 for more details 
https://jinja.palletsprojects.com/en/2.11.x/

```python


class EmailSchema(BaseModel):
    email: List[EmailStr]
    body: Dict[str, Any]

conf = ConnectionConfig(
    MAIL_USERNAME = "YourUsername",
    MAIL_PASSWORD = "strong_password",
    MAIL_FROM = "your@email.com",
    MAIL_PORT = 587,
    MAIL_SERVER = "your mail server",
    MAIL_TLS = True,
    MAIL_SSL = False,
    TEMPLATE_FOLDER='./email templates folder'
)


@app.post("/email")
async def send_with_template(email: EmailSchema) -> JSONResponse:

    message = MessageSchema(
        subject="Fastapi-Mail module",
        recipients=email.dict().get("email"),  # List of recipients, as many as you can pass 
        body=email.dict().get("body"),
        subtype="html"
        )

    fm = FastMail(conf)
    await fm.send_message(message, template_name="email_template.html") #optional field template_name is the name of the html file(jinja template) to use from the email template folder
    return JSONResponse(status_code=200, content={"message": "email has been sent"})


```

The library is fantastic, great job!

**Comment by maestro-1** [comment]
My pull request is ready when you are

**Comment by sabuhish** [comment]
Thank you so much for your words! it become great with help of contributors. I was thinking about jinja when I first started writing the module, thought maybe make simple at first then later I will dive into Jinja as well. Here it is, cool I liked the idea you submitted. It will make the library more aweosme. 

I highly appreciate your given time and working on it. I will go review the codebase again, will merge your PR with the newer version we will have the availability of  Jinja2 HTML Templates.

**Comment by ngoduykhanh** [comment]
Hi @maestro-1,

Thank you for your contribution to the module. As far as I can see, the message's `body` in this case is a `dict`. However, when I try with that, I got the following error. Do you have any idea or a working example that I can follow?

```
  File "/Users/hidden/python3.8/site-packages/fastapi_mail/fastmail.py", line 47, in send_message
    msg = await self.__preape_message(message)
  File "/Users/hidden/python3.8/site-packages/fastapi_mail/fastmail.py", line 34, in __preape_message
    return await msg._message(self.config.MAIL_FROM)
  File "/Users/hidden/python3.8/site-packages/fastapi_mail/msg.py", line 95, in _message
    self.message.attach(self._mimetext(self.body))
  File "/Users/hidden/python3.8/site-packages/fastapi_mail/msg.py", line 38, in _mimetext
    return MIMEText(text, _subtype=self.subtype, _charset=self.charset)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/email/mime/text.py", line 42, in __init__
    self.set_payload(_text, _charset)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/email/message.py", line 321, in set_payload
    self.set_charset(charset)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/email/message.py", line 364, in set_charset
    payload = payload.encode('ascii', 'surrogateescape')
AttributeError: 'dict' object has no attribute 'encode'
```

**Comment by ngoduykhanh** [comment]
nvm, it was because of the invalid template directory path. Fixed it. There should be a warning message for this case though :)

**Comment by maestro-1** [comment]
Yeah, I am working to make some improvements. My next PR should also raise the exception in case of an invalid template directory.
