### ISSUE TITLE
Sending mail with files "noname" and no extension.

### ISSUE THREAD

**Issue by MiguelGoiss** [sabuhish/fastapi-mail#210]
I'm testing the fastapi-mail module for the first time. I tried using the route to send files from the documentation and every time I get the filename on the mail with "noname" and no extension.
This is what I get on the email when I send the email:
![image](https://github.com/sabuhish/fastapi-mail/assets/114920371/ed381c03-ffc0-4a6e-86dd-80d7eeb6e7d3)

**Comment by sabuhish** [comment]
Pls check doc. Maybe the file you are sending has some issues, normally this I how I send:

```@app.post("/file")
async def send_file(
    background_tasks: BackgroundTasks,
    file: UploadFile = File(...),
) -> JSONResponse:

    message = MessageSchema(
        subject="Fastapi mail module",
        recipients=["sabuhi.shukurov@gmail.com"],
        body="Simple background task",
        subtype=MessageType.html,
        attachments=[file],
    )

    fm = FastMail(conf)
    # await fm.send_message(message=message)

    background_tasks.add_task(fm.send_message, message)

    return JSONResponse(status_code=200, content={"message": "email has been sent"})
```
