### ISSUE TITLE
Authentification working locally - not on staging aws serveur

### ISSUE THREAD

**Issue by TheFashionBook** [sabuhish/fastapi-mail#212]
Hello guys,

I have an issue when sending an emai from my staging serveur (aws) : authentification error see below :
fastapi_mail.errors.ConnectionErrors: Exception raised (535, '5.7.8 Error: authentication failed: UGFzc3dvcmQ6'), check your credentials or email service configuration
`Exception raised (535, '5.7.8 Error: authentication failed: UGFzc3dvcmQ6'), check your credentials or email service configuration`

I'm able to send email from my local computer with exactly the same credentials. My email is a professional one from Hostinger.

If somebody has an idea about this.

Thank you very much

**Comment by sabuhish** [comment]
Hello, you should check your firewall or check credentials, this is not on library level.
