### ISSUE TITLE
how to use fm = FastMail(conf) 

### ISSUE THREAD

**Issue by CHRISTOPHERKADOGO** [sabuhish/fastapi-mail#213]
I want check  if the email  is  not  successfully  delivered  to  intended recipients.  maybe due to  wrong email address or something else

**Comment by sabuhish** [comment]
if it is wrong email, or not found it will raise an error.

**Comment by CHRISTOPHERKADOGO** [comment]
how  can I  configure it  to  raise  such exception @sabuhish
