### ISSUE TITLE
Features utils

### ISSUE THREAD

**Issue by Turall** [sabuhish/fastapi-mail#26]
I would like to have some additional features of this module. For example, check MX records, whether the address is temporary. I would like to add a blocking email address or domain

**Comment by sabuhish** [comment]
Sounds interesting, we would love to have this feature. Indeed, this will be helpful.

**Comment by Turall** [comment]
I will later create a PR for this issue. At the moment I am testing these features.

**Comment by sabuhish** [comment]
cool we are waiting!
