### ISSUE TITLE
[Question] Gmail "MAIL_USERNAME" ConnectionConfig

### ISSUE THREAD

**Issue by ihsanmohamad** [sabuhish/fastapi-mail#28]
How do i use gmail alias with "MAIL_USERNAME"? Using gmail, i keep getting bad credential error.

What i'm trying to achieve is 
SportJom <sportjom@gmail.com>

but that was not possible if my "MAIL_USERNAME" is not the email address.

For "MAIL_USERNAME" I have to use my full email address as the username. Is this just gmail issue?

**Comment by sabuhish** [comment]
use SportJom in MAIL_FROM attribute and MAIL_USERNAME  sportjom@gmail.com

**Comment by ihsanmohamad** [comment]
> use SportJom in MAIL_FROM_NAME attribute and MAIL_USERNAME [sportjom@gmail.com](mailto:sportjom@gmail.com)

thank you for that, I just realised that I have MAIL_FROM_NAME option in the new version. However it seems like I need to have both MAIL_FROM and MAIL_FROM_NAME, else it would throw pydantic error "MAIL_FROM field required".

![mail](https://user-images.githubusercontent.com/32008268/100118856-2f256100-2eb1-11eb-90c1-0843c245d7c7.PNG)

The second email is the one that I received using fastapi-mail, while the first one received from me manually sending the email.

**Comment by sabuhish** [comment]
Yes exactly, we discussed this at #16 It is available as new feeature. you are required to provide MAIL_FROM as well.

**Comment by ihsanmohamad** [comment]
Hi yes, I did that and the result is like from the image from my previous reply with the second email. How do I achieve the result like the first email? 

Here is how I setup my config
![mail2](https://user-images.githubusercontent.com/32008268/100122204-11a5c680-2eb4-11eb-95e9-9de961a45d67.PNG)

My current setting will also include my email. I would like to get result like this SportJom <sportjom.my@g mail.com>

Thank you and sorry for the inconveniences!

**Comment by Turall** [comment]
> Hi yes, I did that and the result is like from the image from my previous reply with the second email. How do I achieve the result like the first email?
> 
> Here is how I setup my config
> ![mail2](https://user-images.githubusercontent.com/32008268/100122204-11a5c680-2eb4-11eb-95e9-9de961a45d67.PNG)
> 
> My current setting will also include my email. I would like to get result like this SportJom <sportjom.my@g mail.com>
> 
> Thank you and sorry for the inconveniences!

Hi @ihsanmohamad, thank you for using fastapi-mail. 
I tested your method and it worked.
Here is how I setup my config:
![gmail](https://user-images.githubusercontent.com/32899328/100143739-32b7e880-2eaf-11eb-9d1d-b8a05585e232.png)

and I got the email as you wanted:
![email](https://user-images.githubusercontent.com/32899328/100143918-73affd00-2eaf-11eb-8bd1-c6463c76a90f.png)
Can you explain the situation in more detail?

**Comment by Turall** [comment]
> > use SportJom in MAIL_FROM_NAME attribute and MAIL_USERNAME [sportjom@gmail.com](mailto:sportjom@gmail.com)
> 
> thank you for that, I just realised that I have MAIL_FROM_NAME option in the new version. However it seems like I need to have both MAIL_FROM and MAIL_FROM_NAME, else it would throw pydantic error "MAIL_FROM field required".
> 
> ![mail](https://user-images.githubusercontent.com/32008268/100118856-2f256100-2eb1-11eb-90c1-0843c245d7c7.PNG)
> 
> The second email is the one that I received using fastapi-mail, while the first one received from me manually sending the email.

but if you want to receive an email and the sender's name then you can correct the config when you send an email

here is an example:
![new_gmail](https://user-images.githubusercontent.com/32899328/100146230-07cf9380-2eb3-11eb-9d5c-4807d8bef334.png)

and the result is:
![new_email](https://user-images.githubusercontent.com/32899328/100146281-174edc80-2eb3-11eb-976d-fba7a49d8af6.png)

**Comment by ihsanmohamad** [comment]
Oh my god, I felt stupid and embarrassed. Turns out it was my windows mail having that result. On my gmail opened from web, it works as expected.  Even though I just knew about MAIL_FROM_NAME new attribute in the latest release (i was using release 0.2.8.5), I can't believe it was such a stupid mistake coming from the windows mail. 

**Sorry for the trouble, thank you so much for providing assistance to me. Much appreciated.**

**Comment by Turall** [comment]
Happy to see you resolved the issue. Thing happens, it is okay :) at least you figured out the problem

**Comment by rextech03** [comment]
I have been struggling with send email using this module but I always get this error: fastapi_mail.errors.ConnectionErrors: Exception 
raised Error connecting to smtp.gmail.com on port 587: [Errno 10061] Connect call failed ('74.125.140.109', 587), check your credentials or email service configuration.
I have checked my login detail but all to no avail
![Capture](https://user-images.githubusercontent.com/41661166/147368825-f2ad82aa-f184-4d64-b96a-1b7fec9c5db0.PNG)

**Comment by rextech03** [comment]
I have been struggling with send email using this module but I always get this error: fastapi_mail.errors.ConnectionErrors: Exception
raised Error connecting to smtp.gmail.com on port 587: [Errno 10061] Connect call failed ('74.125.140.109', 587), check your credentials or email service configuration.
I have checked my login detail but all to no avail
![Capture](https://user-images.githubusercontent.com/41661166/147368861-b1c1e395-458f-471d-9bcd-094b26e37274.PNG)

**Comment by Carlos-err406** [comment]
im having an issue similar to @rextech03 's
`Exception raised (535, '5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials 78-20020a250d51000000b00b7767ca7487sm181675ybn.36 - gsmtp'), check your credentials or email service configuration
`

using this configuration, that has worked for some
![photo_2023-03-23_22-47-20](https://user-images.githubusercontent.com/81443707/227411468-6e899107-45d2-4a33-a3a6-8fc946de87c4.jpg)

**Comment by Carlos-err406** [comment]
> im having an issue similar to @rextech03 's `Exception raised (535, '5.7.8 Username and Password not accepted. Learn more at\n5.7.8 https://support.google.com/mail/?p=BadCredentials 78-20020a250d51000000b00b7767ca7487sm181675ybn.36 - gsmtp'), check your credentials or email service configuration `
> 
> using this configuration, that has worked for some ![photo_2023-03-23_22-47-20](https://user-images.githubusercontent.com/81443707/227411468-6e899107-45d2-4a33-a3a6-8fc946de87c4.jpg)

sorry i just noticed this isn't actually a problem with fastapi-mail is just that Google security is very tight, just tried with a different mail server and worked like a charm
