### ISSUE TITLE
Adding a custom sender_title

### ISSUE THREAD

**Issue by YveOms** [sabuhish/fastapi-mail#31]
Is it possible to add a custom sender title  to the connection config

**Comment by sabuhish** [comment]
Yes, it is possible, we had a discussion here at #28 . I hope that helps

**Comment by YveOms** [comment]
Please take a look at this. 
![image](https://user-images.githubusercontent.com/28395700/101121553-7625fb80-3601-11eb-8038-390167a13f66.png)

The above error is produced each time I attempt to add the  MAIL_FROM_NAME item to the config dictionary
conf.MAIL_FROM_NAME = "YveOms"

**Comment by Turall** [comment]
> Please take a look at this.
> ![image](https://user-images.githubusercontent.com/28395700/101121553-7625fb80-3601-11eb-8038-390167a13f66.png)
> 
> The above error is produced each time I attempt to add the MAIL_FROM_NAME item to the ConnectionConfig
> conf.MAIL_FROM_NAME = "YveOms"

This problem is not related with conf.MAIL_FROM_NAME, you generally cannot connect to the server.

**Comment by sabuhish** [comment]
@Turall  is right, it is not related to MAIL_FROM_NAME. you have not been providing correct information for your mail server. It exactly mentions why the error occurs.

**Comment by YveOms** [comment]
@Turall Thank you guys for your support. But then, when I do not include the MAIL_FROM_NAME, the mail is sent successfully. When I try to include the MAIL_FROM_NAME, the above error occurs. I am using Zoho Mail

**Comment by sabuhish** [comment]
I can't reproduce, can you provide a version of the module? and can you post a repository that replicates this?
