### ISSUE TITLE
test_redis_config failing

### ISSUE THREAD

**Issue by maestro-1** [sabuhish/fastapi-mail#33]
@Turall 
The unit test for test_redis_checker in test_redis_config fails with` ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 6379)`
 I speculate it is because I do not have a Redis server turned on and I believe it might be a little better if you used mocking in conjunction with those partcular tests: I would rather not have to turn on a Redis server everytime I want to run a test for fastapi-mail.

**Comment by Turall** [comment]
> @Turall
> The unit test for test_redis_checker in test_redis_config fails with` ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 6379)`
> I speculate it is because I do not have a Redis server turned on and I believe it might be a little better if you used mocking in conjunction with those partcular tests: I would rather not have to turn on a Redis server everytime I want to run a test for fastapi-mail.

Yes, you are right because you do not have a Redis server. I am thinking of using a [https://pypi.org/project/fakeredis/](url) to fix this.
