### ISSUE TITLE
SMTP Relay doesn't Work

### ISSUE THREAD

**Issue by jaimebustose** [sabuhish/fastapi-mail#35]
I try to connect to a SMTP Relay server without MAIL_PASSWORD, then authentication fails and throws an Exception:

`python
Exception raised {error}, check your credentials or email service configuration
`

This is presumably because it requires the username and password when authenticating, but for SMTP Relay it is not required both.

**Comment by sabuhish** [comment]
@jaimebustose  does #36 fix your issue, can we close it now?

**Comment by jaimebustose** [comment]
Yep the change its work regards!!
