### ISSUE TITLE
Question: Queuing of bulk messages

### ISSUE THREAD

**Issue by hithismani** [sabuhish/fastapi-mail#37]
Most email providers have a rate limit (eg: SES has a 14 mails per second limit), that MAY get trigerred by the background function.

Is there a way to perhaps "Queue" things up in FastAPI itself, without having to rely on celery/redis? Don't think I'll reach this limit so soon, but you can never be too sure. 

What do y'all suggest?

Thanks again, for creating this!

**Comment by maestro-1** [comment]
Typically the best alternative would be a background task, this comes default with fastapi.

```python
from fastapi import BackgroundTasks, FastAPI

app = FastAPI()


def write_notification(email: st):
    #Your code. Possibly one that is time dependent


@app.post("/send-notification/{email}")
async def send_notification(email: str, background_tasks: BackgroundTasks):
    background_tasks.add_task(write_notification, email, message="some notification")
    return {"message": "Notification sent in the background"}

```

This is the inbuilt way of handling tasks if you would not like to use third-party tools. This is not exactly recommended for very heavy time-consuming tasks.

**Comment by sabuhish** [comment]
Thank you @maestro-1  for the great answer! I think he already clarified what to do. FastApi has great class BackgroundTasks which you can manipulate your emails with it. Python's multiprocessing module also quite useful in this case.
