### ISSUE TITLE
beginners guide

### ISSUE THREAD

**Issue by PureDreamer** [sabuhish/fastapi-mail#40]
Hey I don't know if it is ok to ask but, I tried to copy the examples and changed them to my own credentials, yet it still doesn't work
can you please put on a beginners guide or something, so it would be easier to access?
Thanks in advance!

**Comment by sabuhish** [comment]
Hey! 

We have an example section in the documentation:
https://sabuhish.github.io/fastapi-mail/example/ 

Used by also might be useful:
https://github.com/sabuhish/fastapi-mail/network/dependents?package_id=UGFja2FnZS04NDkzOTc0MjE%3D

if you still face any issues, post here we can troubleshoot together.

**Comment by PureDreamer** [comment]
I really appreciate your work!
Yet I found things to be not explained thoroughly, like in the example of sending emails
why does it have to be a dict in the recipients?
do I have to use MessageSchema?
Thank you for your patience!

**Comment by PureDreamer** [comment]
how can I send an email in the background and stay on the same page?

**Comment by sabuhish** [comment]
Thanks.  I feel documentation is well designed. May be you should  read fastapi pydantic documentation before dive in, by then you can work around easily.
It doesn't have to be dict. Not a single statements mentions this, it is only list.
Ajax request from client side can help you to stay in the page.
