### ISSUE TITLE
Send local attachments

### ISSUE THREAD

**Issue by UtopiaBe** [sabuhish/fastapi-mail#41]
Hello, How can i send files from local directory?
when i give a "./app/files/file.pdf" path, I receive this error:

`AttributeError: 'bytes' object has no attribute 'read'`

or

`attachments field type incorrect, must be UploadFile or path`

**Comment by Turall** [comment]
Hi @UtopiaBe ,
Thank you for using fastapi-mail. Yes this a bug, and we fix it at in this PR. In the latest version it will be available.

**Comment by Turall** [comment]
```
class EmailSchema(BaseModel):
    email: List[EmailStr]
    file: List[str]


conf = ConnectionConfig(
    MAIL_USERNAME = "YourUsername",
    MAIL_PASSWORD = "strong_password",
    MAIL_FROM = "your@email.com",
    MAIL_PORT = 587,
    MAIL_SERVER = "your mail server",
    MAIL_TLS = True,
    MAIL_SSL = False,
    USE_CREDENTIALS = True
)

app = FastAPI()


@app.post("/email")
async def simple_send(email: EmailSchema) -> JSONResponse:

    message = MessageSchema(
        subject="Fastapi-Mail module",
        recipients=email.email,  # List of recipients, as many as you can pass 
        body="simple file",
        attachments=email.file
        )

    fm = FastMail(conf)
    await fm.send_message(message)
    return JSONResponse(status_code=200, content={"message": "email has been sent"})


This is a simple example, maybe it will help you. 
The request body will look like

{
  "email": [
    "user@example.com"
  ],
  "file": ["/path/to/your/file.pdf"]
}

The file must be in the root of the project because we are checking file path in case path traversal

**Comment by sabuhish** [comment]
Thank you @Turall  for the nice explanation and example you're provided! @UtopiaBe  this should solve your problem.

**Comment by UtopiaBe** [comment]
Thank you @Turall  and @sabuhish!
Its workking :)

But when I attach a local file, the filename in attachment shows the path, not the filename only:
![mail](https://user-images.githubusercontent.com/29890009/105577994-ca3d9880-5d85-11eb-9e2c-5512e2f71e7d.PNG)

code:
`    
   pdf = "./app/pdf_agreements/destination.pdf"

    message = MessageSchema(
        subject="test",
        recipients=["mail@gmail.com"],
        body="body",
        attachments=[pdf]
    )
    fm = FastMail(MAIL)
    await fm.send_message(message)

    return dict(detail="success")
    
   

`

**Comment by sabuhish** [comment]
Please check version 0.3.4.2.

**Comment by sabuhish** [comment]
@UtopiaBe  does this release fixes your issue?

**Comment by UtopiaBe** [comment]
@sabuhish Yes it is!
Great job guys! Keep it up :P

**Comment by VISHNU-P-M** [comment]
```
message = MessageSchema(subject=subject,
recipients=[ "test@gmail.com"],
subtype="html",
template_body=body,
attachments=['path-to-local-file'])
```
                                                   
```
fm = FastMail(conf)
await self.fm.send_message(message=self.message, template_name='index.html')
```

this returning me error
```too many values to unpack (expected 2)```
while attaching file
