### ISSUE TITLE
Jinja2 templates not getting populated with body

### ISSUE THREAD

**Issue by fletcheaston** [sabuhish/fastapi-mail#46]
I'm trying to send an HTML rendered email with Jinja2 templates, but no context is being send.

Here's an example of the message I'm sending...

```
message = MessageSchema(
    subject="Grove Password Reset",
    recipients=[form.email],
    body={"email": email, "other": "some random string"},
    subtype="html",
)

fast_mail = FastMail(settings.EMAIL_CONFIG)

background_tasks.add_task(fast_mail.send_message, message, template_name="template.html")
```

The email is sent correctly, and the template shows up as a rendered HTML email, but none of the information from the body parameter gets rendered.

**Comment by fletcheaston** [comment]
Temporary solution is to use f-strings. Fortunately, setting the subtype to html still works to render those strings as html.

**Comment by sabuhish** [comment]
https://github.com/sabuhish/fastapi-mail/issues/21
@maestro-1  has done a great job on that.  #21 has an example as well. What you are missing is specifying TEMPLATE_FOLDER in your config.

**Comment by wajeshubham** [comment]
you can access body dict keys in your html template as follows:

<p>{{ body.other }}</p> 

it will render :some random string" in your template

**Comment by sabuhish** [comment]
Thanks @wajeshubham for the explanation as well!  As I see we gave examples, it should be now clear. if you have other issues please re-open the new issue.

**Comment by Nikhilbk1705** [comment]
> Thanks @wajeshubham for the explanation as well! As I see we gave examples, it should be now clear. if you have other issues please re-open the new issue.

Hello Sir, I am trying to render html inside the the body using f string email is sent correctly but in the body, the html is displayed as the plain text along with html element as attached in below screenshot
![issue](https://user-images.githubusercontent.com/75827502/149884186-0913535e-0981-41bf-84ab-6743b1a8a76a.png)

**Comment by Nikhilbk1705** [comment]
> Hello Sir, I am trying to render html inside the the body using f string email is sent correctly but in the body, the html is displayed as the plain text along with html element as attached in below screenshot

Hello Sir, I am trying to render html inside the the body using f string email is sent correctly but in the body, the html is displayed as the plain text along with html element as attached in below screenshot
![issue](https://user-images.githubusercontent.com/75827502/149885340-c6b2f20c-65df-4211-a282-1b7e0b0e89d3.png)

**Comment by Nikhilbk1705** [comment]
> > Hello Sir, I am trying to render html inside the the body using f string email is sent correctly but in the body, the html is displayed as the plain text along with html element as attached in below screenshot
> 
> Hello Sir, I am trying to render html inside the the body using f string email is sent correctly but in the body, the html is displayed as the plain text along with html element as attached in below screenshot ![issue](https://user-images.githubusercontent.com/75827502/149885340-c6b2f20c-65df-4211-a282-1b7e0b0e89d3.png)

This can be solved by using "html" field instead of "body "  in message scheme

**Comment by reinaldoBloopark** [comment]
@Nikhilbk1705 can you show me an example? 
Do you mean:
message = MessageSchema(
        subject=subject,
        recipients=[email_to],
        html="<p> Thanks</p>",
        subtype='html',
    )
