### ISSUE TITLE
trying to connect with flag SUPPRESS_SEND=1

### ISSUE THREAD

**Issue by ikasymov** [sabuhish/fastapi-mail#52]
I noticed if set SUPPRESS_SEND=1 and trying to call 
```
fm = FastMail(settings.email_config)
fm.config.SUPPRESS_SEND = 1
fm.send_message(schema)
```
so under the hood its work like this 
```
async with Connection(self.config) as session:
    if not self.config.SUPPRESS_SEND:
        await session.session.send_message(msg)
```
In theory, it may work correctly and is useful, but in practice gitlab CI pytest pipelines can't even open a session and this code crashes with error ConnectionErrors.
I wanna not even open the connection when SUPPRESS_SEND = 1 is specified.

**Comment by sabuhish** [comment]
@ikasymov did you check the documentation for testing?

https://sabuhish.github.io/fastapi-mail/example/#unittests-using-fastapimail

**Comment by ikasymov** [comment]
@sabuhish Yes, but in test mode, fastapi-mail will still open a connection session.
https://github.com/sabuhish/fastapi-mail/blob/master/fastapi_mail/fastmail.py#L88.
in this case fastapi-mail checks for conditions only after opening a connection. 
I think that in test mode fastapi-mail does't need to open a connection at all.

**Comment by sabuhish** [comment]
Nope no need to open the connection session. Let me paste the following code it can help you around.

conftest.py

```
import pytest
from fastapi.testclient import TestClient
from app import FastMail, conf,app

@pytest.fixture
def client():
    
    client = TestClient(app)
    yield client

@pytest.fixture
def fm():
    
    mail = FastMail(conf)
    mail.config.SUPPRESS_SEND = 1
    return mail
   ```
   
  test_mail.py
  ```

def test_email(client, fm):
    with fm.record_messages() as outbox:
        response = client.get("/email")
        assert len(outbox) == 1
        outbox[0]["Subject"] == "Fastapi-Mail module"
```
  app.py
  
  ```
  
  

@app.get("/email")
async def simple_send() -> JSONResponse:

    message = MessageSchema(
        subject="Fastapi-Mail module",
        recipients=["your_mail"],  # List of recipients, as many as you can pass 
        body=template,
        subtype="html"
        )

    fm = FastMail(conf)
    await fm.send_message(message)
    return JSONResponse(status_code=200, content={"message": "email has been sent"})     
    ```

**Comment by sabuhish** [comment]
> I think that in test mode fastapi-mail does't need to open a connection at all.

yes, exactly no needed to open a connection in test mode. But the line you sent opens a connection beforehand. this will be fixed. I was using the right credentials, did not thought of using random test users. Thanks for reporting
