### ISSUE TITLE
Enabling UTF-8

### ISSUE THREAD

**Issue by Timusan** [sabuhish/fastapi-mail#55]
Thanks for the awesome library, it makes emails a little less painful again!

However, I have an issue when my SMTP password contains a currency symbol (€) which results in the following error:

```
fastapi_mail.errors.ConnectionErrors: Exception raised 'ascii' codec can't encode character '\u20ac' in position 10: ordinal not in range(128), check your credentials or email service configuration
```

In "plain" smtplib you would make sure that you enable UTF-8, but how do I tell FastAPI-Mail to handle credentials (and/or even the template) using UTF-8?

**Comment by sabuhish** [comment]
Thanks for your nice words!

Yes, that is right. fastapi-mail is on top of  [aiosmtplib](https://github.com/cole/aiosmtplib). I was checking the source code for authentication, password, and username is encoded to ascii in the aiosmtplib.  
Here is the line:
https://github.com/cole/aiosmtplib/blob/main/aiosmtplib/auth.py#L118

Let's move this issue to aiosmtplib, see if we can have work around this.

**Comment by Timusan** [comment]
Awesome @sabuhish, thanks for the research and reporting this to [aiosmtplib](https://github.com/cole/aiosmtplib)!
