### ISSUE TITLE
Which protocol uses fastapi-mail?

### ISSUE THREAD

**Issue by ArtemDavletov** [sabuhish/fastapi-mail#62]
Hello to all members! I have a question, it's a bit not clear for me. Which protocol uses fastapi-mail for sending messages to SMTP server? Is it SMTP or HTTPS or smt else?
```python
await fm.send_message(message)
```

**Comment by Turall** [comment]
Hi @ArtemDavletov , 
fastapi-mail sends messages over an SMTP protocol.

**Comment by ArtemDavletov** [comment]
Thank you!
