### ISSUE TITLE
path_traversal throwing TemplateFolderDoesNotExist for pyenv virtualenv

### ISSUE THREAD

**Issue by andrews-CS** [sabuhish/fastapi-mail#69]
I maintain all my python venvs with pyenv and the function 'path_traversal' is throwing an error when it tries to resolve the current config file path so that it can validate (I assume) it's not something malicious.
![image](https://user-images.githubusercontent.com/38673780/123560833-1767df80-d7e8-11eb-95ba-e608103c8bee.png)

Here, the 2 paths that are checked are always different because my pyenv path is in the global .pyenv folder:
![image](https://user-images.githubusercontent.com/38673780/123560858-35354480-d7e8-11eb-9f0e-5ec95bda7332.png)

Is there a way around this?

**Comment by sabuhish** [comment]
As documentation mentions this it should be like this `TEMPLATE_FOLDER = Path(__file__).parent / 'templates'`
   Pls refer to the documentation: https://sabuhish.github.io/fastapi-mail/example.html#using-jinja2-html-templates

**Comment by andrews-CS** [comment]
ah thank you, I missed that, closing issue
