### ISSUE TITLE
path_traversal with venv

### ISSUE THREAD

**Issue by netstuff** [sabuhish/fastapi-mail#70]
Hello! 

I'm using `poetry` and got an issue with `TEMPLATE_FOLDER` option with exception `TemplateFolderDoesNotExist` because it not pass [path_traversal](https://github.com/sabuhish/fastapi-mail/blob/master/fastapi_mail/config.py#L50) check.

After debug I found out that:
-  `base = Path(__file__).parent.parent` inside `path_traversal` equals to `PosixPath('/Users/netstuff/Sites/mailout/api/.venv/lib/python3.9/site-packages')`
- passed to `TEMPLATE_FOLDER` path equals to `PosixPath('/Users/netstuff/Sites/mailout/api/src/mailout/templates/mail')`

What can I do with it?
Thank you.

**Comment by kucera-lukas** [comment]
Hi,

the path traversal check is indeed broken, for now you could just monkey patch that function to always return `True`, (`fastapi_mail.config.path_traversal = lambda *args, **kwargs: True`).

I think that doing `base = Path(os.getcwd())` should fix the issue.

**Comment by netstuff** [comment]
@kucera-lukas thank u very much! I have already done it ;)

**Comment by Turall** [comment]
Hi @netstuff,  can you share your config file without creds. ?
project template folder should be at the root of the project or in subfolders.
```
conf = ConnectionConfig(
       ...
    TEMPLATE_FOLDER="./templates"
)
```
or 
```
conf = ConnectionConfig(
       ...
    TEMPLATE_FOLDER="testpython"
)
```
or
```
conf = ConnectionConfig(
       ...
    TEMPLATE_FOLDER="./templates/html/"
)
```

**Comment by netstuff** [comment]
Hi @Turall !

Here is my config (private settings is hidden by `MAIL_SETTINGS`)
```python
ConnectionConfig(
    **MAIL_SETTINGS,
    TEMPLATE_FOLDER=PosixPath('/Users/netstuff/project/api/src/templates/mail'),
    SUPPRESS_SEND=1,
    USE_CREDENTIALS=True,
    VALIDATE_CERTS=True
)
```

**Comment by Turall** [comment]
> Hi @Turall !
> 
> Here is my config (private settings is hidden by `MAIL_SETTINGS`)
> 
> ```python
> ConnectionConfig(
>     TEMPLATE_FOLDER=PosixPath('/Users/netstuff/project/api/src/templates/mail'),
>     SUPPRESS_SEND=1,
>     USE_CREDENTIALS=True,
>     VALIDATE_CERTS=True,
>     **MAIL_SETTINGS
> )
> ```

if your project root folder is `project` you must set `TEMPLATE_FOLDER="./api/src/templates/mail"`

**Comment by Turall** [comment]
@netstuff could you solve your problem?

**Comment by sabuhish** [comment]
@Turall thanks for your help. He is right you should not set the full path, set it from the project root foler.  @netstuff  do you still face the same error?
Also one more suggestion to use:

``` TEMPLATE_FOLDER = Path(__file__).parent / 'template_folder',```

**Comment by francois-travais** [comment]
I'm facing the same issue than @netstuff , and `TEMPLATE_FOLDER = Path(__file__).parent / 'template_folder'` doesn't work. I had to disable the `path_traversal` as @kucera-lukas suggested.
