### ISSUE TITLE
email being sent with the html code

### ISSUE THREAD

**Issue by ayushven** [sabuhish/fastapi-mail#73]
I am sending an email with html code, which in receiver's end being received as html code and render of that html.

**Comment by ayushven** [comment]
An email sent through the example
<img width="336" alt="Screenshot 2021-07-06 at 3 17 39 PM" src="https://user-images.githubusercontent.com/73475523/124580093-67404980-de6d-11eb-82a9-f825cd03c7e1.png">

**Comment by tindzk** [comment]
I encountered the same problem. It works if you use `html` instead of `body`:

```python
    message = MessageSchema(
        subject="Contact form",
        recipients=["info@example.com"],
        html="<b>HTML body</b>",
        subtype="html"
    )
```

**Comment by sabuhish** [comment]
@tindzk thanks for helping, as I see the issue has been resolved we can close it.
