### ISSUE TITLE
 connections limit

### ISSUE THREAD

**Issue by jet10000** [sabuhish/fastapi-mail#75]
aiosmtplib.errors.SMTPDataError: (432, '4.3.2 Concurrent connections limit exceeded. Visit https://aka.ms/concurrent_sending for more information. [Hostname=OS0PR01MB6099.jpnprd01.prod.outlook.com]')

Is there a Queue for tasks?

**Comment by sabuhish** [comment]
Nope actually there is no such functionality, but how many connections you have established?
