### ISSUE TITLE
Update from fastapi-mail==0.3.7 to 0.4

### ISSUE THREAD

**Issue by kot6egemot** [sabuhish/fastapi-mail#77]
HelIo, Hi.  I updated  requirements.txt from 0.3.7 to 0.4 in my app. And it is not working now with such error.
I'm running in Docker container FROM python:3.
This folder exactly existing. 
![image](https://user-images.githubusercontent.com/41436209/125930207-34088d3c-05cd-435b-924f-cf97e21fbb42.png)
But i try to do set up folder as '/' and it will be some.

**Comment by Turall** [comment]
can you check this issue #70 , I wrote here about this error
