### ISSUE TITLE
Is it possible to enable DEBUG?

### ISSUE THREAD

**Issue by netstuff** [sabuhish/fastapi-mail#78]
I see attribute `MAIL_DEBUG` in `ConnectionConfig` but it not using in code.
How can I print email message to log rather than send to recipients?

**Comment by maestro-1** [comment]
conf = ConnectionConfig(
    MAIL_USERNAME = "YourUsername",
    MAIL_PASSWORD = "strong_password",
    MAIL_FROM = "your@email.com",
    MAIL_PORT = 587,
    MAIL_SERVER = "your mail server",
    MAIL_TLS = True,
    MAIL_SSL = False,
    TEMPLATE_FOLDER = Path(__file__).parent / 'templates',

    # if no indicated SUPPRESS_SEND defaults to 0 (false) as below
    # SUPPRESS_SEND=1
)


In fastapi-mail the way to use debug mode is to set SUPPRESS_SEND to 1. This prevents emails from being sent and you can log your messages as you see fit. Check out the unites section at the bottom of the example [page](https://sabuhish.github.io/fastapi-mail/example.html) page for a more clear outlook of how to use SUPPRESS_SEND
