### ISSUE TITLE
MessageSchema body can't pass dict

### ISSUE THREAD

**Issue by ahmetkca** [sabuhish/fastapi-mail#81]
conf` = ConnectionConfig(
    MAIL_USERNAME = MAIL_EMAIL,
    MAIL_PASSWORD = MAIL_PASSWORD,
    MAIL_FROM = MAIL_EMAIL,
    MAIL_PORT = MAIL_PORT,
    MAIL_SERVER = MAIL_HOST,
    MAIL_TLS = True,
    MAIL_SSL = False,
    USE_CREDENTIALS = True,
	TEMPLATE_FOLDER = './templates'
)

body={
		'verification_code': inserted_email_invitation['verification_code'],
		'register_email_url': email_invitation_link.format(
					email=inserted_email_invitation['email'],
					verification_code=inserted_email_invitation['verification_code'])}
	ms = get_mail_service()
	message = MessageSchema(
        subject="[OrderAIO] - Register - Verification Code",
        recipients=[inserted_email_invitation['email']],
        body=body,
        subtype='html',
    )
background_tasks.add_task(ms.send_message, message, `template_name="verification_email.html")

pydantic.error_wrappers.ValidationError: 2 validation errors for MessageSchema
body
  str type expected (type=type_error.str)
body
  value is not a valid list (type=type_error.list)

**Comment by Turall** [comment]
Hi @ahmetkca , You can pass dict to template_body when using jinja templates
