### ISSUE TITLE
Showing raw html as well as the html code in string mail with subtype html

### ISSUE THREAD

**Issue by Mitra-Electronics** [sabuhish/fastapi-mail#83]
Showing raw html as well as the html code in string mail with subtype html
![Screenshot 2021-08-15 205527](https://user-images.githubusercontent.com/72347115/129483617-1af3bbb9-373f-41e6-817c-faa0f4187f31.png)

**Comment by Turall** [comment]
hi @Mitra-Electronics, please provide an example of your code.

**Comment by Mitra-Electronics** [comment]
`from fastapi import FastAPI, BackgroundTasks, UploadFile, File, Form
from starlette.responses import JSONResponse
import uvicorn
from starlette.requests import Request
from fastapi_mail import FastMail, MessageSchema,ConnectionConfig
from pydantic import BaseModel, EmailStr
from typing import List



class EmailSchema(BaseModel):
    email: List[EmailStr]


conf = ConnectionConfig(
    MAIL_USERNAME = "email",
    MAIL_PASSWORD = "app password",
    MAIL_FROM = "email",
    MAIL_PORT = 587,
    MAIL_SERVER = "smtp.gmail.com",
    MAIL_TLS = True,
    MAIL_SSL = False,
    USE_CREDENTIALS = True,
    VALIDATE_CERTS = True,
)

app = FastAPI()


html = """
<p>Thanks for using Fastapi-mail</p> 
"""


@app.post("/email")
async def simple_send(email: EmailSchema) -> JSONResponse:

    message = MessageSchema(
        subject="Fastapi-Mail module",
        recipients=email.dict().get("email"),  # List of recipients, as many as you can pass 
        body=html,
        subtype="html"
        )

    fm = FastMail(conf)
    await fm.send_message(message)
    return JSONResponse(status_code=200, content={"message": "email has been sent"})

if __name__ == "__main__":
    uvicorn.run("fr:app", reload=True)`
I have entered my details of the email configuration in `conf` in my actual script

**Comment by sabuhish** [comment]
use html https://github.com/sabuhish/fastapi-mail/issues/73

**Comment by Mitra-Electronics** [comment]
Thanks, I actually didn't see the #73 issue

**Comment by akuehnis** [comment]
It would be fantastic if this possibility would be mentioned in documentation page, examples and the MessageSchema class description. Thanks!
https://pypi.org/project/fastapi-mail/
https://sabuhish.github.io/fastapi-mail/example/
https://sabuhish.github.io/fastapi-mail/getting-started/#fastmail-class
