### ISSUE TITLE
Mypy Stub file not found

### ISSUE THREAD

**Issue by jd-0001** [sabuhish/fastapi-mail#88]
Hi,

Thanks for this package.  I use mypy in my development env along with VSCode. After installation I am getting:

```
Stub file not found for "fastapi_mail"
```

when I import from `fastapi_mail`.

![Screenshot from 2021-09-09 16-23-22](https://user-images.githubusercontent.com/47495003/132673418-2d7df08c-c6c6-457e-848e-6e81a08db9a0.png)

![Screenshot from 2021-09-09 16-23-50](https://user-images.githubusercontent.com/47495003/132673609-a275afaf-63ab-4674-959d-dcef7ea41066.png)

**Comment by maestro-1** [comment]
Hi @jd-0001 
This is likely an issue with mypy and or your system and not with FastApi_mail

**Comment by jd-0001** [comment]
Does this works in your case? I am using VSCode

**Comment by maestro-1** [comment]
Yes, it does work on my VSCode

**Comment by jd-0001** [comment]
Hi @maestro-1 @Turall 

I am still getting the same error. Can you please share your `mypy.ini` file?
