### ISSUE TITLE
fastapi 0.70.0 

### ISSUE THREAD

**Issue by clerkzhang** [sabuhish/fastapi-mail#98]
fastapi 0.70.0

 Because fastapi-mail (1.0.1) depends on fastapi (>=0.68.1,<0.69.0)
   and no versions of fastapi-mail match >1.0.1,<2.0.0, fastapi-mail (>=1.0.1,<2.0.0) requires fastapi (>=0.68.1,<0.69.0).
  So, because hashjump co api depends on both fastapi (^0.70.0) and fastapi-mail (^1.0.1), version solving failed.

**Comment by freewayz** [comment]
Can we get this merged in?

**Comment by minddust** [comment]
this! +1

**Comment by restureese** [comment]
this +1

**Comment by Feijo** [comment]
They might be looking for contributors. Can anybody put together a PR for this?

**Comment by justb4** [comment]
Changes  FastAPI 0.68.* to 0.70.0 seem minor, mainly package upgrades: 
https://fastapi.tiangolo.com/release-notes/#0700

**Comment by sabuhish** [comment]
Hey there, sorry for being late was not around( Could you please check and confirm everything works as expected with new version (1.0.2). I have upgraded fastapi version to 0.70.0

**Comment by justb4** [comment]
Thanks @sabuhish ! This works for me: `fastapi==0.70.0 fastapi-mail==1.0.2`. Using like:
```
        message = MessageSchema(
            subject=subject,
            recipients=to_emails,
            body=html,
            subtype='html',
        )

        fm = FastMail(EMAIL_CONF)
        await fm.send_message(message)
```
Have not checked other options like background tasks and attachments.

Possibly unrelated but I receive all HTML email (both in desktop mailer and gmail) as `Content-Type: multipart/mixed; charset="utf-8";` with parts: `Content-Type: text/plain;  charset="utf-8"` and `Content-Type: text/html; charset="utf-8"`.
The mail shows both as text with html-tags and formatted HTML.
Gmail regards that email as spam.

**Comment by gvisniuc** [comment]
@sabuhish since this issue is still open, if it's not too much of a hassle would it be possible to bump the version to 0.71.0 because of https://github.com/tiangolo/fastapi/issues/4041#issuecomment-1007951986.

```
#11 60.33 The conflict is caused by:
#11 60.33     The user requested fastapi==0.71.0
#11 60.33     fastapi-mail 1.0.2 depends on fastapi==0.70.0
```

Thanks!

**Comment by ia-Simon** [comment]
This would be great! I'm really looking forward for using FastAPI with Python 3.10 on one of my company's projects.
